### ISSUE TITLE
json.decoder.JSONDecodeError when import pandasgui

### ISSUE THREAD

**Issue by andrewmabc** [adamerose/PandasGUI#126]
PLEASE FILL OUT THE TEMPLATE

**Describe the bug**  
use the following code, and python reports error

import pandas as pd
from pandasgui import show
df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
show(df)

error message:

Traceback (most recent call last):
  File "test_pandagui.py", line 2, in <module>
    from pandasgui import show
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\__init__.py", line 15, in <module>
    from pandasgui.gui import show
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\gui.py", line 13, in <module>
    from pandasgui.store import PandasGuiStore, PandasGuiDataFrameStore
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\store.py", line 550, in <module>
    SETTINGS_STORE = SettingsStore()
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\store.py", line 96, in __init__
    saved_settings = read_saved_settings()
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\store.py", line 35, in read_saved_settings
    saved_settings = json.load(f)
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Environment**
OS: (eg. Windows 10)
Python: (eg. 3.8.4)
IDE: (eg. PyCharm)

**Package versions**  

install anaconda environment

dependencies:
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py38haa95532_0
  - openssl=1.1.1k=h2bbff1b_0
  - pip=21.0.1=py38haa95532_0
  - python=3.8.8=hdbf39b2_4
  - setuptools=52.0.0=py38haa95532_0
  - sqlite=3.35.2=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - pip:
    - appdirs==1.4.4
    - astor==0.8.1
    - backcall==0.2.0
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==4.4.2
    - et-xmlfile==1.0.1
    - future==0.18.2
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - kiwisolver==1.3.1
    - matplotlib==3.4.0
    - numexpr==2.7.3
    - numpy==1.20.1
    - openpyxl==3.0.7
    - pandas==1.2.3
    - pandasgui==0.2.10.1
    - pandastable==0.12.2.post1
    - parso==0.8.1
    - pickleshare==0.7.5
    - pillow==8.1.2
    - plotly==4.14.3
    - prompt-toolkit==3.0.18
    - pyarrow==3.0.0
    - pygments==2.8.1
    - pynput==1.7.3
    - pyparsing==2.4.7
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyqtwebengine==5.15.4
    - pyqtwebengine-qt5==5.15.2
    - python-dateutil==2.8.1
    - pytz==2021.1
    - retrying==1.3.3
    - six==1.15.0
    - tkintertable==1.3.2
    - traitlets==5.0.5
    - wcwidth==0.2.5
    - wordcloud==1.8.1
    - xlrd==2.0.1
    - xlsxwriter==1.3.7
    - xlwt==1.3.0

**Comment by adamerose** [comment]
Seems like the json file that locally caches your settings got corrupted and can't be read. I'm not sure how it got corrupted... maybe I could tell if you shared the file?  Run this snippet to see the location

```
import os
from pandasgui.constants import LOCAL_DATA_DIR
preferences_path = os.path.join(LOCAL_DATA_DIR, 'preferences.json')
print(preferences_path)
```

Deleting that file should fix the error

**Comment by fdion** [comment]
I've had one user getting this exact error. He did say that Windows crashed just as he was exiting pandasgui. I fixed it by deleting the preferences file. might not be a bad idea to try/except the load and delete the preference file in that case.

**Comment by andrewmabc** [comment]
The following code still fails to run

import os
from pandasgui.constants import LOCAL_DATA_DIR
preferences_path = os.path.join(LOCAL_DATA_DIR, 'preferences.json')
print(preferences_path)

error message

Traceback (most recent call last):
  File "D:/working/excel_python/compare_excel_00001/test_pandagui.py", line 7, in <module>
    from pandasgui.constants import LOCAL_DATA_DIR
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\__init__.py", line 15, in <module>
    from pandasgui.gui import show
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\gui.py", line 13, in <module>
    from pandasgui.store import PandasGuiStore, PandasGuiDataFrameStore
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\store.py", line 550, in <module>
    SETTINGS_STORE = SettingsStore()
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\store.py", line 96, in __init__
    saved_settings = read_saved_settings()
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\site-packages\pandasgui\store.py", line 35, in read_saved_settings
    saved_settings = json.load(f)
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\analyze_excel\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
